"""Orchestration of retrieval and generation."""

from __future__ import annotations

import logging
from dataclasses import dataclass, field

from langchain_core.documents import Document

from .config import Settings
from .embeddings import build_embeddings
from .llm import BedrockLLMClient
from .retriever import retrieve
from .vector_store import create_client, open_collection

LOGGER = logging.getLogger(__name__)


@dataclass(frozen=True)
class AnswerResult:
    """Result of a single question.

    Attributes:
        question: The question that was asked.
        answer: The text generated by the LLM.
        chunks: The chunks the answer was generated from.
    """

    question: str
    answer: str
    chunks: list[Document] = field(default_factory=list)


def answer_question(settings: Settings, question: str) -> AnswerResult:
    """Answers a single question from the indexed documents.

    Steps: open the collection written by cvbot-embedder, retrieve the top-k
    chunks for the question and let the Bedrock model generate an answer from
    them. Conversation history is not taken into account.

    Args:
        settings: Runtime configuration.
        question: The user question.

    Returns:
        The generated answer together with the chunks it is based on.

    Raises:
        ValueError: If the question is empty.
    """
    embeddings = build_embeddings(settings)
    client = create_client(settings)
    store = open_collection(client, settings.collection_name, embeddings)
    chunks = retrieve(store, question, settings.top_k)

    llm = BedrockLLMClient(settings)
    answer = llm.generate(build_prompt(question, chunks))

    LOGGER.info(
        "answered question from %d chunk(s), %d answer character(s)",
        len(chunks),
        len(answer),
    )
    return AnswerResult(question=question, answer=answer, chunks=chunks)


def build_prompt(question: str, chunks: list[Document]) -> str:
    """Combines question and chunks into a single prompt.

    Placeholder until iteration 2 introduces system prompt and history.

    Args:
        question: The user question.
        chunks: The retrieved chunks.

    Returns:
        The prompt passed to the LLM.
    """
    context = "\n\n".join(chunk.page_content for chunk in chunks)
    return f"Context:\n{context}\n\nQuestion: {question}"
