"""Orchestration of retrieval, context management and generation."""

from __future__ import annotations

import logging
import uuid
from dataclasses import dataclass, field

from cvbot_core.embeddings import build_bedrock_embeddings
from langchain_core.documents import Document

from .config import Settings
from .context import build_context
from .conversation import (
    ROLE_USER,
    ConversationStore,
    InMemoryConversationStore,
    Message,
)
from .llm import BedrockLLMClient
from .prompts import SYSTEM_PROMPT, build_user_message
from .query_condensation import condense_question
from .retriever import retrieve
from .vector_store import create_client, get_indexed_embedding_model_id, open_collection

LOGGER = logging.getLogger(__name__)


@dataclass(frozen=True)
class AnswerResult:
    """Result of a single turn.

    Attributes:
        question: The question that was asked.
        answer: The text generated by the LLM.
        chunks: The chunks the answer was generated from.
        conversation_id: Identifier of the conversation the turn belongs to.
    """

    question: str
    answer: str
    chunks: list[Document] = field(default_factory=list)
    conversation_id: str = ""


class ConversationEngine:
    """Answers questions within a conversation.

    Embedding model, collection and Bedrock client are created once and reused
    for every turn. The full history lives in the ``ConversationStore``, while
    the context sent to the model is derived per turn and may be shorter.
    """

    def __init__(
        self,
        settings: Settings,
        store: ConversationStore | None = None,
    ) -> None:
        """Opens the collection written by cvbot-embedder.

        Args:
            settings: Runtime configuration.
            store: Storage of the conversations; defaults to a process-local
                one.
        """
        self._settings = settings
        self._store = store or InMemoryConversationStore()
        client = create_client(settings)
        embedding_model_id = get_indexed_embedding_model_id(
            client, settings.collection_name
        )
        embeddings = build_bedrock_embeddings(
            model_id=embedding_model_id, region_name=settings.aws_region
        )
        self._collection = open_collection(
            client, settings.collection_name, embeddings
        )
        self._llm = BedrockLLMClient(settings)

    @property
    def store(self) -> ConversationStore:
        """Returns the store holding the full histories."""
        return self._store

    def answer(self, conversation_id: str, question: str) -> AnswerResult:
        """Answers a question as the next turn of a conversation.

        Retrieves the matching chunks, derives a context that fits into the
        token budget, generates the answer and appends both turns to the full
        history. Only the current question carries retrieved chunks; earlier
        turns are kept as plain text so that the history stays displayable.
        Retrieval itself is based on a standalone version of the question: a
        dedicated model call resolves references to earlier turns (e.g. "und
        davor?") before the question is embedded, while the model that
        generates the answer still sees the original wording.

        Args:
            conversation_id: Identifier of the conversation.
            question: The user question.

        Returns:
            The generated answer together with the chunks it is based on.

        Raises:
            ValueError: If the question is empty or if system prompt and
                question alone exceed the context budget.
        """
        conversation = self._store.load(conversation_id)
        history = conversation.history()
        search_query = condense_question(self._llm, history, question)
        chunks = retrieve(self._collection, search_query, self._settings.top_k)
        current = Message(
            role=ROLE_USER, content=build_user_message(question, chunks)
        )

        context = build_context(
            system_prompt=SYSTEM_PROMPT,
            history=history,
            current_message=current,
            max_context_tokens=self._settings.max_context_tokens,
            response_token_buffer=self._settings.response_token_buffer,
        )
        answer = self._llm.generate(context, system=SYSTEM_PROMPT)

        conversation.add_user(question)
        conversation.add_assistant(answer)
        self._store.save(conversation)

        LOGGER.info(
            "answered turn %d of conversation %s from %d chunk(s)",
            len(conversation.messages),
            conversation_id,
            len(chunks),
        )
        return AnswerResult(
            question=question,
            answer=answer,
            chunks=chunks,
            conversation_id=conversation_id,
        )


def answer_question(settings: Settings, question: str) -> AnswerResult:
    """Answers a single question without any previous history.

    Args:
        settings: Runtime configuration.
        question: The user question.

    Returns:
        The generated answer together with the chunks it is based on.

    Raises:
        ValueError: If the question is empty.
    """
    engine = ConversationEngine(settings)
    return engine.answer(str(uuid.uuid4()), question)
